<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>compressed_image_decoder</name>
  <version>0.1.0</version>
  <description>
    Decodes `sensor_msgs/CompressedImage` messages into `sensor_msgs/Image` messages using
    `ffmpeg_encoder_decoder` library. Works for H.265/HEVC or H.264 compressed streams, and uses
    hardware acceleration if available.
  </description>
  <maintainer email="anas.saeed@bonsairobotics.ai">Anas Saeed</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>sensor_msgs</depend>
  <depend>ffmpeg_encoder_decoder</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
